task:
  name: nightly x86_64-unknown-freebsd-10
  freebsd_instance:
    image: freebsd-10-4-release-amd64 
  setup_script:
    - pkg install -y curl
    - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs --output rustup.sh
    - sh rustup.sh --default-toolchain nightly -y --profile=minimal
    - . $HOME/.cargo/env
    - rustup default nightly
  test_script:
    - . $HOME/.cargo/env
    - cargo build --verbose
    - cargo test --all --all-features -- --nocapture

task:
  name: stable x86_64-unknown-freebsd-11
  freebsd_instance:
    image: freebsd-11-3-stable-amd64-v20190801
  setup_script:
    - pkg install -y curl
    - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs --output rustup.sh
    - sh rustup.sh -y --profile=minimal
    - . $HOME/.cargo/env
    - rustup default stable
  test_script:
    - . $HOME/.cargo/env
    - cargo build --verbose
    - cargo test --all --all-features -- --nocapture

task:
  name: nightly x86_64-unknown-freebsd-12
  freebsd_instance:
    image: freebsd-12-0-release-amd64
  setup_script:
    - pkg install -y curl
    - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs --output rustup.sh
    - sh rustup.sh --default-toolchain nightly -y --profile=minimal
    - . $HOME/.cargo/env
    - rustup default nightly
  test_script:
    - . $HOME/.cargo/env
    - cargo build --verbose
    - cargo test --all --all-features -- --nocapture
