language: rust
rust:
  - 1.20.0 # MSRV
  - nightly
  - beta
  - stable
jobs:
  allow_failures:
    - rust: nightly
script:
  - cargo build --verbose
  - cargo test --all --all-features -- --nocapture
