sudo: false
language: rust
rust:
  - nightly
  - beta
  - stable
matrix:
  allow_failures:
    - rust: nightly
script:
  - cargo build --verbose
  - cargo test --all --all-features -- --nocapture
addons:
  apt:
    packages:
    - libcurl4-openssl-dev
    - libelf-dev
    - libdw-dev
