name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build_and_test:
    strategy:
      fail-fast: false
      matrix:
        toolchain:
          - x86_64-unknown-linux-gnu
          - i686-unknown-linux-gnu
          - x86_64-pc-windows-msvc
          - x86_64-pc-windows-gnu
          - i686-pc-windows-msvc
          - x86_64-apple-darwin
        version:
          - 1.31.1 # MSRV
          - stable
          - nightly
        include:
        - toolchain: x86_64-unknown-linux-gnu
          os: ubuntu-22.04
        - toolchain: i686-unknown-linux-gnu
          os: ubuntu-22.04
        - toolchain: x86_64-pc-windows-msvc
          os: windows-2022
        - toolchain: x86_64-pc-windows-gnu
          os: windows-2022
        - toolchain: i686-pc-windows-msvc
          os: windows-2022
        - toolchain: x86_64-apple-darwin
          os: macos-12

    name: ${{ matrix.version }} - ${{ matrix.toolchain }}
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Install packages for 32bit environment
        if: matrix.toolchain == 'i686-unknown-linux-gnu'
        run: sudo apt install gcc-multilib g++-multilib -y

      - name: Install ${{ matrix.version }}
        run: rustup override set ${{ matrix.version }}-${{ matrix.toolchain }}

      - run: cargo build

      - name: tests
        run: cargo test -- --nocapture
