name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build_and_test:
    strategy:
      fail-fast: false
      matrix:
        toolchain:
          - x86_64-unknown-linux-gnu
          - x86_64-pc-windows-msvc
          - x86_64-pc-windows-gnu
          - aarch64-apple-darwin
          - x86_64-apple-darwin
        version:
          - 1.85.0 # MSRV
          - stable
          - nightly
        include:
        - toolchain: x86_64-unknown-linux-gnu
          os: ubuntu-latest
        - toolchain: x86_64-pc-windows-msvc
          os: windows-latest
        - toolchain: x86_64-pc-windows-gnu
          os: windows-latest
        - toolchain: aarch64-apple-darwin
          os: macos-latest
        - toolchain: x86_64-apple-darwin
          os: macos-latest

    name: ${{ matrix.version }} - ${{ matrix.toolchain }}
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Install ${{ matrix.version }}
        run: rustup override set ${{ matrix.version }}-${{ matrix.toolchain }}

      - run: cargo build

      - name: tests
        run: cargo test -- --nocapture
