name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build_and_test:
    strategy:
      fail-fast: false
      matrix:
        toolchain:
          - x86_64-unknown-linux-gnu
          - i686-unknown-linux-gnu
          - x86_64-pc-windows-msvc
          - x86_64-pc-windows-gnu
          - i686-pc-windows-msvc
          - x86_64-apple-darwin
        version:
          - 1.31.1 # MSRV
          - stable
          - nightly
        include:
        - toolchain: x86_64-unknown-linux-gnu
          os: ubuntu-latest
        - toolchain: i686-unknown-linux-gnu
          os: ubuntu-latest
        - toolchain: x86_64-pc-windows-msvc
          os: windows-latest
          arch: x64
        - toolchain: x86_64-pc-windows-gnu
          os: windows-latest
        - toolchain: i686-pc-windows-msvc
          os: windows-latest
          arch: x86
        - toolchain: x86_64-apple-darwin
          os: macOS-latest

    name: ${{ matrix.version }} - ${{ matrix.toolchain }}
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@master

      - name: Install packages for 32bit environment
        if: matrix.toolchain == 'i686-unknown-linux-gnu'
        run: sudo apt-get install gcc-multilib g++-multilib -y

      - name: Install ${{ matrix.version }}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.version }}-${{ matrix.toolchain }}
          default: true

      - name: cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --all --bins --examples --tests

      - name: tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all --all-features -- --nocapture
