name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  check_platform_support:
    strategy:
      fail-fast: false
      matrix:
        toolchain:
          # Tier 2
          - x86_64-apple-ios
          - x86_64-fuchsia
          - x86_64-linux-android
          - x86_64-sun-solaris
          - x86_64-unknown-freebsd
          - x86_64-unknown-netbsd
          - x86_64-unknown-redox
          # Tier 3
          - x86_64-unknown-bitrig
          - x86_64-unknown-dragonfly
          - x86_64-unknown-openbsd
          - x86_64-unknown-haiku

    name: ${{ matrix.toolchain }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.toolchain }}
          default: true
          profile: minimal

      - name: cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --all --bins --examples --tests

      - name: tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all --all-features -- --nocapture
